const movies = [
    {title: "The Lion King", emojis: "🦁👑🌍🐗🦓🐒🐘🌅🎶"},
    {title: "The Hunger Games", emojis: "🏹👧🔥🍞🌲🏞️🏟️🤝📺💥🏆"},
    {title: "Schindler's List", emojis: "📓🚂🏭👨‍👩‍👧‍👦💰🛤️💌🕊️"},
    {title: "Inception", emojis: "💤🌀💼🏢🧠🕰️🚂🌊🏔️🏨"},
    {title: "The Shawshank Redemption", emojis: "🏢🔒📖👬🔨⛈️🕳️🏃🏝️💵"},
    {title: "The Godfather", emojis: "👨‍👩‍👧‍👦🔫🐴💼🌹🩸🎬💰"},
    {title: "Pulp Fiction", emojis: "🔫💼🍔🕶️💃🕺💉⚰️💰📖"},
    {title: "Forrest Gump", emojis: "🏃👟🚌🍤🏈🇺🇸🚁💏👪"},
    {title: "The Dark Knight", emojis: "🦇🌃🃏🔥🏦🚁🚔👊💥🦸"},
    {title: "Fight Club", emojis: "🤝🥊💥🏢🧼🔥🕵️‍♂️💣💭🌀"},
    { title: "The Matrix", emojis: "💻🕶️📞🔫🏃‍♂️🏢🥋🚁🕋🔌" },
    { title: "The Lord of the Rings: The Fellowship of the Ring", emojis: "💍🧙‍♂️🧝‍♂️🌋🏹⚔️🛡️🌄🕷️🔥" },
    { title: "The Godfather: Part II", emojis: "🇮🇹👨‍👩‍👧‍👦🔫💼🌹🃏🛥️🚬💣" },
    { title: "The Empire Strikes Back", emojis: "🌌⚔️🚀🤖❄️👽💫🛸👨‍🚀👹" },
    { title: "Interstellar", emojis: "👨‍🚀🌾🚀🌀🌌🌕🌊⌛🌍👨‍👩‍👧" },
    { title: "Goodfellas", emojis: "🇮🇹👨‍👩‍👧‍👦🔫💰🚬🚔🚁👮‍♂️🐀" },
    { title: "The Green Mile", emojis: "🏢🔒👨‍🦼🐀🤲🌩️💔🪓⚰️🕊️" },
    { title: "Gladiator", emojis: "🛡️⚔️👑🏟️🐯🔥🏛️👊💀🌹" },
    { title: "The Silence of the Lambs", emojis: "🕵️‍♀️🦋🔪👮‍♀️🔒👹🐑🔦🏚️🩸" },
    { title: "The Usual Suspects", emojis: "💥🚢🔫🕵️‍♂️🚬🃏👥🚔🎭🔚" },
    { title: "Se7en", emojis: "🕵️‍♂️🔎📦🔪🩸💀🐖🔥⚖️🚔" },
    { title: "Eternal Sunshine of the Spotless Mind", emojis: "💔💤🧠📼🌊❄️🚉🎢🌅💞" }
];